window.FORMA_DATA={
recipes:[
{id:'b1',cat:'breakfast',name:'Proteinowa owsianka',kcal:509,p:33,f:10,c:73,ingredients:['Płatki owsiane 50 g','Skyr naturalny 200 g','Banan 100 g','Masło orzechowe 10 g','Owoce jagodowe 100 g'],steps:['Płatki zalej wodą lub ugotuj.','Dodaj skyr po lekkim przestudzeniu.','Na wierzch banan, owoce i masło orzechowe.']},
{id:'b2',cat:'breakfast',name:'Jajka + tosty + indyk',kcal:503,p:48,f:15,c:46,ingredients:['Jajka 2 szt.','Białka jaj 150 g','Pieczywo 90 g','Szynka z indyka 60 g'],steps:['Jajka i białka usmaż na nieprzywierającej patelni.','Pieczywo podpiecz.','Zjedz z szynką i warzywami według uznania.']},
{id:'b3',cat:'breakfast',name:'Skyr crunch',kcal:522,p:40,f:6,c:79,ingredients:['Skyr 300 g','Płatki kukurydziane 50 g','Banan 100 g','Masło orzechowe 10 g'],steps:['Wszystko wrzuć do miski.','Masło orzechowe rozprowadź na wierzchu.','Gotowe w 2 minuty.']},
{id:'b4',cat:'breakfast',name:'Tosty z serkiem wiejskim',kcal:544,p:46,f:17,c:58,ingredients:['Pieczywo 100 g','Serek wiejski 200 g','Szynka z indyka 60 g','Awokado 30 g'],steps:['Pieczywo podpiecz.','Nałóż serek, indyka i awokado.','Dopraw pieprzem, czosnkiem lub chili.']},
{id:'b5',cat:'breakfast',name:'Pancake bowl',kcal:508,p:45,f:9,c:61,ingredients:['Płatki owsiane 50 g','Jajko 1 szt.','Białka jaj 150 g','Skyr 150 g','Banan 100 g'],steps:['Zblenduj płatki, jajko, białka i pół banana.','Usmaż małe placuszki bez dodatkowego tłuszczu.','Podaj ze skyrem i resztą banana.']},
{id:'l1',cat:'lunch',name:'Kurczak + ryż + warzywa',kcal:689,p:53,f:14,c:85,ingredients:['Ryż suchy 90 g','Pierś z kurczaka 180 g','Oliwa 10 g','Warzywa 250 g'],steps:['Ugotuj ryż.','Kurczaka dopraw i usmaż lub zrób w airfryerze.','Warzywa podsmaż na części oliwy, wszystko połącz.']},
{id:'l2',cat:'lunch',name:'Beef rice bowl',kcal:676,p:49,f:16,c:81,ingredients:['Ryż suchy 85 g','Wołowina mielona 5% 180 g','Oliwa 5 g','Warzywa 250 g'],steps:['Ugotuj ryż.','Wołowinę mocno dopraw: papryka, kmin, czosnek, chili.','Dodaj warzywa i podaj z ryżem.']},
{id:'l3',cat:'lunch',name:'Kurczak + ziemniaki z airfryera',kcal:741,p:55,f:14,c:97,ingredients:['Ziemniaki 500 g','Pierś z kurczaka 180 g','Oliwa 10 g','Warzywa 200 g'],steps:['Ziemniaki pokrój, wymieszaj z oliwą i przyprawami.','Airfryer ok. 190°C do chrupkości.','Kurczaka zrób obok lub na patelni, dodaj warzywa.']},
{id:'l4',cat:'lunch',name:'Makaron z kurczakiem',kcal:654,p:57,f:13,c:75,ingredients:['Makaron suchy 90 g','Pierś z kurczaka 180 g','Oliwa 8 g','Warzywa 200 g'],steps:['Ugotuj makaron al dente.','Kurczaka podsmaż z czosnkiem, chili i ziołami.','Dodaj warzywa, makaron i odrobinę wody z gotowania.']},
{id:'l5',cat:'lunch',name:'Łosoś + ziemniaki',kcal:752,p:48,f:24,c:80,ingredients:['Ziemniaki 400 g','Łosoś 180 g','Warzywa 200 g'],steps:['Ziemniaki ugotuj lub zrób w airfryerze.','Łososia dopraw solą, pieprzem, cytryną i piecz 12–16 min.','Podaj z dużą porcją warzyw.']},
{id:'l6',cat:'lunch',name:'Burrito wołowe',kcal:719,p:50,f:16,c:90,ingredients:['Tortilla 70 g','Wołowina mielona 5% 160 g','Ryż suchy 50 g','Jogurt naturalny 80 g','Warzywa 150 g'],steps:['Ugotuj ryż i podsmaż mocno doprawioną wołowinę.','Jogurt wymieszaj z czosnkiem i solą.','Zawiń wszystko w tortillę i podsmaż z obu stron.']},
{id:'s1',cat:'snack',name:'Skyr + banan + masło orzechowe',kcal:353,p:33,f:8,c:41,ingredients:['Skyr 250 g','Banan 120 g','Masło orzechowe 15 g'],steps:['Wrzuć wszystko do miski.','Opcjonalnie cynamon i słodzik.']},
{id:'s2',cat:'snack',name:'Serek wiejski + wafle',kcal:403,p:28,f:9,c:56,ingredients:['Serek wiejski 200 g','Wafle ryżowe 40 g','Banan 80 g'],steps:['Serek dopraw na słodko lub słono.','Wafle i banana zjedz obok.']},
{id:'s3',cat:'snack',name:'Shake + płatki',kcal:369,p:34,f:6,c:44,ingredients:['Odżywka białkowa 30 g','Mleko 1,5% 250 ml','Płatki kukurydziane 35 g'],steps:['Zblenduj odżywkę z mlekiem.','Płatki zjedz osobno albo wrzuć do gęstszego shake’a.']},
{id:'s4',cat:'snack',name:'Skyr bowl z miodem',kcal:401,p:36,f:2,c:59,ingredients:['Skyr 300 g','Owoce jagodowe 150 g','Miód 20 g','Wafle ryżowe 20 g'],steps:['Skyr i owoce do miski.','Dodaj miód, wafle pokrusz na wierzch.']},
{id:'s5',cat:'snack',name:'Tosty proteinowe',kcal:376,p:36,f:10,c:39,ingredients:['Pieczywo 70 g','Serek wiejski 150 g','Szynka z indyka 60 g'],steps:['Pieczywo podpiecz.','Dodaj serek i indyka.','Dopraw według uznania.']},
{id:'d1',cat:'dinner',name:'Quesadilla z kurczakiem',kcal:763,p:68,f:18,c:79,ingredients:['Tortille 120 g','Pierś z kurczaka 160 g','Mozzarella light 60 g','Jogurt naturalny 80 g','Warzywa 150 g'],steps:['Kurczaka podsmaż z przyprawami.','Na tortillę daj kurczaka, mozzarellę i warzywa.','Złóż, podpiecz na suchej patelni, jogurt użyj jako sos.']},
{id:'d2',cat:'dinner',name:'Bowl z tuńczykiem i ryżem',kcal:713,p:59,f:14,c:89,ingredients:['Ryż suchy 90 g','Tuńczyk w sosie własnym 180 g','Awokado 70 g','Warzywa 200 g'],steps:['Ugotuj ryż.','Dodaj odsączonego tuńczyka, awokado i warzywa.','Dopraw sosem sojowym, limonką lub chili.']},
{id:'d3',cat:'dinner',name:'Jajka + ziemniaki',kcal:732,p:46,f:24,c:82,ingredients:['Jajka 3 szt.','Białka jaj 150 g','Ziemniaki 400 g','Oliwa 8 g','Warzywa 200 g'],steps:['Ziemniaki upiecz lub ugotuj.','Jajka i białka usmaż.','Dodaj warzywa i oliwę do ziemniaków.']},
{id:'d4',cat:'dinner',name:'Makaron wołowy',kcal:702,p:54,f:19,c:75,ingredients:['Makaron suchy 90 g','Wołowina mielona 5% 180 g','Oliwa 8 g','Warzywa 200 g'],steps:['Ugotuj makaron.','Wołowinę podsmaż mocno z przyprawami.','Dodaj warzywa i makaron, podlej odrobiną wody.']},
{id:'d5',cat:'dinner',name:'Wrapy z kurczakiem',kcal:759,p:60,f:21,c:82,ingredients:['Tortille 120 g','Pierś z kurczaka 180 g','Jogurt naturalny 100 g','Awokado 40 g','Warzywa 150 g'],steps:['Kurczaka dopraw i podsmaż.','Jogurt wymieszaj z czosnkiem i chili.','Zawiń kurczaka, awokado, warzywa i sos w tortille.']},
{id:'d6',cat:'dinner',name:'Łosoś + ryż',kcal:752,p:48,f:25,c:79,ingredients:['Ryż suchy 80 g','Łosoś 170 g','Warzywa 200 g','Jogurt naturalny 80 g'],steps:['Ugotuj ryż.','Łososia upiecz lub usmaż bez dodatkowego tłuszczu.','Jogurt dopraw czosnkiem i cytryną jako sos.']},
{"id":"b6","cat":"breakfast","name":"Szakszuka z 3 jaj i pieczywem","time":"25 min","difficulty":"Łatwe","ingredients":["Jajka 3 szt.","Pomidory krojone z puszki 300 g","Cebula 70 g","Czosnek 5 g","Oliwa 5 g","Pieczywo 80 g"],"steps":["Posiekaj cebulę i smaż na oliwie na średnim ogniu 4–5 minut. Dodaj czosnek i mieszaj około 30 sekund.","Dodaj pomidory. Dopraw solą, pieprzem, papryką, chili i opcjonalnie kminem. Duś 7–10 minut, aż sos zgęstnieje.","Zrób 3 wgłębienia i wbij jajka. Przykryj i duś na małym ogniu około 5–8 minut, aż białka się zetną.","Podaj z odważonym pieczywem. Możesz zastąpić pomidory 300 g gotowego sosu pomidorowego Culineo; podgrzej go i odparuj do odpowiedniej gęstości."],"nutritionNote":"Wartości orientacyjne na całą porcję, razem z pieczywem, tłuszczem i dodatkami. Jajka: 3 sztuki = około 150 g bez skorupek; pieczywo przyjęto 250 kcal/100 g. Zdjęcie przedstawia propozycję podania — odmierz składniki z listy. Makro dotyczy wersji z pomidorami 24 kcal/100 g. Przy sosie Culineo przelicz według etykiety: zmiana kcal porcji = 3 × (kcal sosu na 100 g − 24).","kcal":566,"p":31,"f":22,"c":56},
{"id":"b7","cat":"breakfast","name":"Jajecznica z pieczywem i warzywami","time":"10 min","difficulty":"Łatwe","ingredients":["Jajka 3 szt.","Białka jaj 100 g","Masło 5 g","Pieczywo 70 g","Warzywa 200 g"],"steps":["Pokrój ogórka i paprykę — razem 200 g. Pieczywo możesz podpiec na suchej patelni.","Na małym ogniu rozpuść 5 g masła. Wbij 3 jajka i dolej 100 g białek jaj.","Dopraw i mieszaj delikatnie 3–5 minut, aż jajka się zetną, ale pozostaną soczyste. Możesz dodać szczypiorek.","Podaj z pieczywem i warzywami."],"nutritionNote":"Wartości orientacyjne na całą porcję, razem z pieczywem, tłuszczem i dodatkami. Jajka: 3 sztuki = około 150 g bez skorupek; pieczywo przyjęto 250 kcal/100 g. Zdjęcie przedstawia propozycję podania — odmierz składniki z listy. Wliczono dodatkowe 100 g białek jaj. Bez nich odejmij około 46 kcal i 10 g białka.","kcal":519,"p":37,"f":21,"c":41},
{"id":"b8","cat":"breakfast","name":"Jajka na twardo z pieczywem i dipem","time":"15 min","difficulty":"Bardzo łatwe","ingredients":["Jajka 3 szt.","Pieczywo 70 g","Skyr naturalny 100 g","Warzywa 200 g"],"steps":["Włóż jajka do garnka i zalej wodą. Od zagotowania gotuj na małym ogniu 9–10 minut.","Zalej zimną wodą, obierz i przekrój jajka na połówki.","Skyr dopraw solą, pieprzem i szczypiorkiem — będzie dipem do jajek i pieczywa.","Podaj z pieczywem oraz pokrojonym ogórkiem i papryką (razem 200 g)."],"nutritionNote":"Wartości orientacyjne na całą porcję, razem z pieczywem, tłuszczem i dodatkami. Jajka: 3 sztuki = około 150 g bez skorupek; pieczywo przyjęto 250 kcal/100 g. Zdjęcie przedstawia propozycję podania — odmierz składniki z listy. Wliczono 100 g skyru jako dip. Bez dipu odejmij około 63 kcal i 11 g białka.","kcal":498,"p":38,"f":17,"c":45},
{"id":"b9","cat":"breakfast","name":"Makrela w pomidorach z pieczywem","time":"5 min","difficulty":"Bardzo łatwe","ingredients":["Makrela w sosie pomidorowym 170 g","Pieczywo 80 g","Ogórek 150 g"],"steps":["Otwórz puszkę i przełóż rybę razem z sosem do miseczki. W przepisie jest 170 g całej zawartości, nie samej odsączonej ryby.","Pokrój ogórka, odważ pieczywo i podaj obok.","Jedz na zimno lub delikatnie podgrzej rybę z sosem w rondelku. Nie dodawaj dodatkowej oliwy ani masła, jeśli chcesz zachować podane makro."],"nutritionNote":"Wartości orientacyjne na całą porcję. Przyjęto makrelę z sosem: 186 kcal, B 13 g, T 12 g, W 5,8 g na 100 g; puszka 170 g. Marki i warianty mocno się różnią — sprawdź etykietę swojej puszki. Pieczywo: 250 kcal/100 g. Zdjęcie to propozycja podania.","nutritionSource":{"label":"Przykładowa etykieta makreli 170 g","url":"https://zakupy.auchan.pl/products/filety-z-makreli-w-sosie-pomidorowym-graal-170-g/00108742"},"kcal":539,"p":30,"f":23,"c":51},
{"id":"l7","cat":"lunch","name":"Ryż z wołowiną i sosem meksykańskim","time":"25 min","difficulty":"Łatwe","ingredients":["Ryż suchy 80 g","Wołowina mielona 5% 180 g","Sos meksykański Culineo 200 g","Oliwa 5 g"],"steps":["Odważ 80 g suchego ryżu i ugotuj według opakowania lub w ryżowarze.","Rozgrzej oliwę. Dodaj wołowinę, rozdrobnij łopatką i smaż około 7–10 minut, aż będzie dokładnie usmażona. Dopraw papryką, czosnkiem i chili.","Wlej 200 g sosu meksykańskiego ze słoika. Mieszaj i podgrzewaj 3–5 minut; jeśli zbyt gęsty, dolej trochę wody.","Podaj z ryżem. Warzywa widoczne w sosie są częścią gotowego produktu — dodatkową kukurydzę lub fasolę dolicz osobno."],"nutritionNote":"Wartości orientacyjne na całą porcję. Ryż ważony na sucho, mięso przed smażeniem. Przyjęto wołowinę 5%: 137 kcal/100 g i sos meksykański: 73,6 kcal, B 1,7 g, T 1,1 g, W 13 g na 100 g. Sprawdź etykiety — tłustsza wołowina i inny sos zmienią wynik. Zdjęcie to propozycja podania.","nutritionSource":{"label":"Orientacyjne dane sosu Culineo","url":"https://www.dine4fit.pl/produkty/sos-meksykanski-culineo"},"kcal":718,"p":47,"f":17,"c":88},
{"id":"l8","cat":"lunch","name":"Tortille z kurczakiem i warzywami","time":"25 min","difficulty":"Łatwe","ingredients":["Tortille 120 g","Pierś z kurczaka 180 g","Jogurt naturalny 100 g","Warzywa 200 g","Czosnek 5 g","Oliwa 5 g"],"steps":["Kurczaka pokrój w paski, dopraw solą, pieprzem, papryką i chili. Smaż na 5 g oliwy około 7–10 minut, aż będzie gotowy w środku.","Pokrój paprykę, ogórka i sałatę — łącznie 200 g. Jogurt wymieszaj z rozgniecionym czosnkiem i dopraw.","Podgrzej 2 tortille o łącznej masie 120 g. Rozłóż na nich kurczaka, warzywa i cały sos.","Zawiń boki i zwiń ciasno. Opcjonalnie podpiecz na suchej patelni po 1–2 minuty z każdej strony. Całe 2 tortille to jedna porcja."],"nutritionNote":"Wartości orientacyjne na całą porcję: 2 tortille, mięso, warzywa i sos. Kurczak ważony na surowo. Przyjęto placki 310 kcal/100 g, jogurt około 2% tłuszczu. Bez sera i majonezu; dodatki dolicz osobno. Zdjęcie to propozycja podania.","kcal":728,"p":58,"f":20,"c":77}
],
weekly:[['Poniedziałek','b4','l5','s2','d4'],['Wtorek','b2','l3','s2','d6'],['Środa','b1','l5','s5','d5'],['Czwartek','b4','l6','s2','d3'],['Piątek','b5','l5','s2','d3'],['Sobota','b3','l5','s5','d6'],['Niedziela','b4','l1','s2','d6']],
training:[
{name:'Poniedziałek — FBW A · akcent klatka',items:[
['1. Wyciskanie sztangi leżąc — klatka / triceps','3×6–8 · RIR 3 w tyg. 1, potem 2'],
['2. Wypychanie nóg na suwnicy (leg press) — czworogłowe / pośladki','3×8–10 · RIR 2–3'],
['3. Wiosłowanie na maszynie z podparciem klatki — plecy','3×8–12 · RIR 2'],
['4. Uginanie nóg siedząc lub leżąc — tył uda','2×10–15 · RIR 2'],
['5. Unoszenie hantli bokiem — boczny akton barków','2×12–20 · RIR 1–2'],
['6. Wspięcia na palce stojąc — łydki','2×10–15 · pauza na dole i górze'],
['7. Prostowanie ramion na wyciągu górnym z liną — triceps','2×10–15 · RIR 1–2'],
['8. Uginanie hantli na ławce skośnej — biceps','2×10–15 · RIR 1–2'],
['9. Spięcia brzucha na wyciągu (cable crunch) — brzuch','2×10–15 · kontrolowany ruch']
]},
{name:'Środa — FBW B · akcent martwy ciąg / plecy',items:[
['1. Martwy ciąg klasyczny — tył ciała / plecy / pośladki','2×4–6 · RIR 3; bez serii do upadku'],
['2. Wyciskanie hantli na ławce skośnej dodatniej — górna klatka','3×8–10 · RIR 2–3'],
['3. Ściąganie drążka wyciągu górnego chwytem neutralnym — najszerszy grzbietu','3×8–12 · RIR 2'],
['4. Przysiad bułgarski — czworogłowe / pośladki','2×8–10 na nogę · RIR 2–3'],
['5. Wyciskanie hantli siedząc nad głowę — barki','2×8–10 · RIR 2'],
['6. Wspięcia na palce siedząc — łydki','2×12–15 · pełny zakres'],
['7. Uginanie ramion ze sztangą EZ — biceps','2×10–15 · RIR 1–2'],
['8. Prostowanie ramion nad głową na wyciągu z liną — triceps','2×10–15 · RIR 1–2'],
['9. Unoszenie kolan w zwisie lub na poręczach — brzuch','2×8–15 · bez bujania']
]},
{name:'Piątek — FBW C · akcent nogi',items:[
['1. Hack squat / przysiad na maszynie — czworogłowe / pośladki','3×6–10 · RIR 2–3'],
['2. Wiosłowanie siedząc na wyciągu dolnym — środek pleców','3×8–12 · RIR 2'],
['3. Rozpiętki na bramie lub pec deck — klatka','2×10–15 · RIR 1–2'],
['4. Hip thrust ze sztangą lub na maszynie — pośladki / tył uda','2×8–12 · RIR 2'],
['5. Odwrotne rozpiętki na maszynie (reverse pec deck) — tylny akton barków','2×12–20 · RIR 1–2'],
['6. Wspięcia na palce stojąc — łydki','2×10–15 · pełny zakres'],
['7. Uginanie ramion na modlitewniku — biceps','2×10–15 · RIR 1–2'],
['8. Prostowanie ramion na wyciągu górnym z liną — triceps','2×10–15 · RIR 1–2'],
['9. Ab wheel / rollout z kółkiem — brzuch','2×6–12 · nie wyginaj lędźwi']
]}
]
};