window.FORMA_DATA={
recipes:[
{id:'b1',cat:'breakfast',name:'Proteinowa owsianka',kcal:509,p:33,f:10,c:73,ingredients:['Płatki owsiane 50 g','Skyr naturalny 200 g','Banan 100 g','Masło orzechowe 10 g','Owoce jagodowe 100 g'],steps:['Płatki zalej wodą lub ugotuj.','Dodaj skyr po lekkim przestudzeniu.','Na wierzch banan, owoce i masło orzechowe.']},
{id:'b2',cat:'breakfast',name:'Jajka + tosty + indyk',kcal:503,p:48,f:15,c:46,ingredients:['Jajka 2 szt.','Białka jaj 150 g','Pieczywo 90 g','Szynka z indyka 60 g'],steps:['Jajka i białka usmaż na nieprzywierającej patelni.','Pieczywo podpiecz.','Zjedz z szynką i warzywami według uznania.']},
{id:'b3',cat:'breakfast',name:'Skyr crunch',kcal:522,p:40,f:6,c:79,ingredients:['Skyr 300 g','Płatki kukurydziane 50 g','Banan 100 g','Masło orzechowe 10 g'],steps:['Wszystko wrzuć do miski.','Masło orzechowe rozprowadź na wierzchu.','Gotowe w 2 minuty.']},
{id:'b4',cat:'breakfast',name:'Tosty z serkiem wiejskim',kcal:544,p:46,f:17,c:58,ingredients:['Pieczywo 100 g','Serek wiejski 200 g','Szynka z indyka 60 g','Awokado 30 g'],steps:['Pieczywo podpiecz.','Nałóż serek, indyka i awokado.','Dopraw pieprzem, czosnkiem lub chili.']},
{id:'b5',cat:'breakfast',name:'Pancake bowl',kcal:508,p:45,f:9,c:61,ingredients:['Płatki owsiane 50 g','Jajko 1 szt.','Białka jaj 150 g','Skyr 150 g','Banan 100 g'],steps:['Zblenduj płatki, jajko, białka i pół banana.','Usmaż małe placuszki bez dodatkowego tłuszczu.','Podaj ze skyrem i resztą banana.']},
{id:'l1',cat:'lunch',name:'Kurczak + ryż + warzywa',kcal:689,p:53,f:14,c:85,ingredients:['Ryż suchy 90 g','Pierś z kurczaka 180 g','Oliwa 10 g','Warzywa 250 g'],steps:['Ugotuj ryż.','Kurczaka dopraw i usmaż lub zrób w airfryerze.','Warzywa podsmaż na części oliwy, wszystko połącz.']},
{id:'l2',cat:'lunch',name:'Beef rice bowl',kcal:676,p:49,f:16,c:81,ingredients:['Ryż suchy 85 g','Wołowina mielona 5% 180 g','Oliwa 5 g','Warzywa 250 g'],steps:['Ugotuj ryż.','Wołowinę mocno dopraw: papryka, kmin, czosnek, chili.','Dodaj warzywa i podaj z ryżem.']},
{id:'l3',cat:'lunch',name:'Kurczak + ziemniaki z airfryera',kcal:741,p:55,f:14,c:97,ingredients:['Ziemniaki 500 g','Pierś z kurczaka 180 g','Oliwa 10 g','Warzywa 200 g'],steps:['Ziemniaki pokrój, wymieszaj z oliwą i przyprawami.','Airfryer ok. 190°C do chrupkości.','Kurczaka zrób obok lub na patelni, dodaj warzywa.']},
{id:'l4',cat:'lunch',name:'Makaron z kurczakiem',kcal:654,p:57,f:13,c:75,ingredients:['Makaron suchy 90 g','Pierś z kurczaka 180 g','Oliwa 8 g','Warzywa 200 g'],steps:['Ugotuj makaron al dente.','Kurczaka podsmaż z czosnkiem, chili i ziołami.','Dodaj warzywa, makaron i odrobinę wody z gotowania.']},
{id:'l5',cat:'lunch',name:'Łosoś + ziemniaki',kcal:752,p:48,f:24,c:80,ingredients:['Ziemniaki 400 g','Łosoś 180 g','Warzywa 200 g'],steps:['Ziemniaki ugotuj lub zrób w airfryerze.','Łososia dopraw solą, pieprzem, cytryną i piecz 12–16 min.','Podaj z dużą porcją warzyw.']},
{id:'l6',cat:'lunch',name:'Burrito wołowe',kcal:719,p:50,f:16,c:90,ingredients:['Tortilla 70 g','Wołowina mielona 5% 160 g','Ryż suchy 50 g','Jogurt naturalny 80 g','Warzywa 150 g'],steps:['Ugotuj ryż i podsmaż mocno doprawioną wołowinę.','Jogurt wymieszaj z czosnkiem i solą.','Zawiń wszystko w tortillę i podsmaż z obu stron.']},
{id:'s1',cat:'snack',name:'Skyr + banan + masło orzechowe',kcal:353,p:33,f:8,c:41,ingredients:['Skyr 250 g','Banan 120 g','Masło orzechowe 15 g'],steps:['Wrzuć wszystko do miski.','Opcjonalnie cynamon i słodzik.']},
{id:'s2',cat:'snack',name:'Serek wiejski + wafle',kcal:403,p:28,f:9,c:56,ingredients:['Serek wiejski 200 g','Wafle ryżowe 40 g','Banan 80 g'],steps:['Serek dopraw na słodko lub słono.','Wafle i banana zjedz obok.']},
{id:'s3',cat:'snack',name:'Shake + płatki',kcal:369,p:34,f:6,c:44,ingredients:['Odżywka białkowa 30 g','Mleko 1,5% 250 ml','Płatki kukurydziane 35 g'],steps:['Zblenduj odżywkę z mlekiem.','Płatki zjedz osobno albo wrzuć do gęstszego shake’a.']},
{id:'s4',cat:'snack',name:'Skyr bowl z miodem',kcal:401,p:36,f:2,c:59,ingredients:['Skyr 300 g','Owoce jagodowe 150 g','Miód 20 g','Wafle ryżowe 20 g'],steps:['Skyr i owoce do miski.','Dodaj miód, wafle pokrusz na wierzch.']},
{id:'s5',cat:'snack',name:'Tosty proteinowe',kcal:376,p:36,f:10,c:39,ingredients:['Pieczywo 70 g','Serek wiejski 150 g','Szynka z indyka 60 g'],steps:['Pieczywo podpiecz.','Dodaj serek i indyka.','Dopraw według uznania.']},
{id:'d1',cat:'dinner',name:'Quesadilla z kurczakiem',kcal:763,p:68,f:18,c:79,ingredients:['Tortille 120 g','Pierś z kurczaka 160 g','Mozzarella light 60 g','Jogurt naturalny 80 g','Warzywa 150 g'],steps:['Kurczaka podsmaż z przyprawami.','Na tortillę daj kurczaka, mozzarellę i warzywa.','Złóż, podpiecz na suchej patelni, jogurt użyj jako sos.']},
{id:'d2',cat:'dinner',name:'Bowl z tuńczykiem i ryżem',kcal:713,p:59,f:14,c:89,ingredients:['Ryż suchy 90 g','Tuńczyk w sosie własnym 180 g','Awokado 70 g','Warzywa 200 g'],steps:['Ugotuj ryż.','Dodaj odsączonego tuńczyka, awokado i warzywa.','Dopraw sosem sojowym, limonką lub chili.']},
{id:'d3',cat:'dinner',name:'Jajka + ziemniaki',kcal:732,p:46,f:24,c:82,ingredients:['Jajka 3 szt.','Białka jaj 150 g','Ziemniaki 400 g','Oliwa 8 g','Warzywa 200 g'],steps:['Ziemniaki upiecz lub ugotuj.','Jajka i białka usmaż.','Dodaj warzywa i oliwę do ziemniaków.']},
{id:'d4',cat:'dinner',name:'Makaron wołowy',kcal:702,p:54,f:19,c:75,ingredients:['Makaron suchy 90 g','Wołowina mielona 5% 180 g','Oliwa 8 g','Warzywa 200 g'],steps:['Ugotuj makaron.','Wołowinę podsmaż mocno z przyprawami.','Dodaj warzywa i makaron, podlej odrobiną wody.']},
{id:'d5',cat:'dinner',name:'Wrapy z kurczakiem',kcal:759,p:60,f:21,c:82,ingredients:['Tortille 120 g','Pierś z kurczaka 180 g','Jogurt naturalny 100 g','Awokado 40 g','Warzywa 150 g'],steps:['Kurczaka dopraw i podsmaż.','Jogurt wymieszaj z czosnkiem i chili.','Zawiń kurczaka, awokado, warzywa i sos w tortille.']},
{id:'d6',cat:'dinner',name:'Łosoś + ryż',kcal:752,p:48,f:25,c:79,ingredients:['Ryż suchy 80 g','Łosoś 170 g','Warzywa 200 g','Jogurt naturalny 80 g'],steps:['Ugotuj ryż.','Łososia upiecz lub usmaż bez dodatkowego tłuszczu.','Jogurt dopraw czosnkiem i cytryną jako sos.']}
],
weekly:[['Poniedziałek','b4','l5','s2','d4'],['Wtorek','b2','l3','s2','d6'],['Środa','b1','l5','s5','d5'],['Czwartek','b4','l6','s2','d3'],['Piątek','b5','l5','s2','d3'],['Sobota','b3','l5','s5','d6'],['Niedziela','b4','l1','s2','d6']],
training:[
{name:'Poniedziałek — Full Body A',items:[['Wyciskanie sztangi leżąc','3×6–8 · RIR 3→2'],['Leg press','3×8–10 · RIR 3→2'],['Wiosłowanie z podparciem klatki','3×8–10'],['RDL','2×8–10'],['Unoszenie bokiem','3×12–20'],['Prostowanie na wyciągu','2×10–15'],['Uginanie na biceps','2×10–15']]},
{name:'Środa — Full Body B',items:[['Wyciskanie hantli skos dodatni','3×8–10'],['Ściąganie drążka wyciągu','3×8–12'],['Hack squat / przysiad na maszynie','3×6–10'],['Uginanie nóg leżąc','3×10–15'],['Shoulder press','2×8–10'],['Wiosłowanie na wyciągu','2×10–12'],['Biceps','2×10–15']]},
{name:'Piątek — Full Body C',items:[['Wyciskanie sztangi leżąc','3×5–7 · technicznie'],['Bułgary / split squat','3×8–10 / noga'],['Ściąganie drążka / podciąganie','3×8–12'],['RDL / martwy na prostych','3×6–8'],['Chest press','2×10–12'],['Unoszenie bokiem','3×12–20'],['Triceps + biceps','2×10–15 każde']]}
]
};