(function(){
function monthKey(r){const d=r.date?new Date(r.date):null;if(d&&!isNaN(d))return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;return `${r.year}-00`;}
function monthLabel(key){if(key.endsWith('-00'))return key.slice(0,4);const [y,m]=key.split('-');return new Intl.DateTimeFormat('pl-PL',{month:'long',year:'numeric'}).format(new Date(Number(y),Number(m)-1,1));}
function buildTrend(reports){const box=document.getElementById('autoTrend');if(!box)return;if(reports.length<2){box.className='verdict muted';box.innerHTML='<h3>Automatyczny trend</h3><p>Potrzebuję co najmniej 2 zapisanych tygodni, żeby ocenić kierunek.</p>';return;}const recent=reports.slice(-4),first=recent[0],last=recent.at(-1);const dw=Number.isFinite(first.avgWeight)&&Number.isFinite(last.avgWeight)?last.avgWeight-first.avgWeight:null;const dp=Number.isFinite(first.waist)&&Number.isFinite(last.waist)?last.waist-first.waist:null;const weeks=Math.max(1,recent.length-1);const rate=Number.isFinite(dw)?dw/weeks:null;let cls='warn',title='Trend mieszany',text='Patrz na kolejne tygodnie i jakość realizacji planu.';
if(Number.isFinite(dw)&&Number.isFinite(dp)&&dw<0&&dp<0){cls='good';title='Trend redukcji jest dobry';text=`W ostatnich ${recent.length} raportach masa zmieniła się o ${dw.toFixed(2)} kg, a pas o ${dp.toFixed(1)} cm.`;if(rate<-0.7)text+=' Tempo masy jest dość szybkie — kontroluj siłę, sen i regenerację.';else if(rate>-0.15)text+=' Spadek jest wolny, ale jeśli pas schodzi i siła wraca, nie ma powodu ciąć kalorii.';else text+=' Tempo jest rozsądne — nie zmieniaj planu bez powodu.';}
else if(Number.isFinite(dw)&&Number.isFinite(dp)&&dw>=0&&dp>=0){cls='bad';title='Trend nie idzie w stronę redukcji';text=`W ostatnich ${recent.length} raportach masa zmieniła się o ${dw.toFixed(2)} kg, a pas o ${dp.toFixed(1)} cm. Jeśli realizacja była dobra przez 2 pełne tygodnie, trzeba będzie skorygować kalorie lub aktywność.`;}
else if(Number.isFinite(dw)&&dw<0){cls='good';title='Masa spada, pas wymaga dalszej obserwacji';text=`Zmiana masy: ${dw.toFixed(2)} kg. Nie reaguj na jeden nietypowy pomiar pasa — oceń kolejny tydzień.`;}
box.className='verdict '+cls;box.innerHTML=`<h3>${title}</h3><p>${text}</p>`;}
const originalRender=window.renderHistory||renderHistory;
window.renderHistory=function(){originalRender();const all=getReports();const filter=document.getElementById('monthFilter');if(!filter)return;const current=filter.value||'all';const keys=[...new Set(all.map(monthKey))].sort().reverse();filter.innerHTML='<option value="all">Wszystkie miesiące</option>'+keys.map(k=>`<option value="${k}">${monthLabel(k)}</option>`).join('');filter.value=keys.includes(current)?current:'all';const selected=filter.value==='all'?all:all.filter(r=>monthKey(r)===filter.value);document.getElementById('historyList').innerHTML=selected.length?[...selected].reverse().map(r=>`<div class="history-item"><b>${r.year} · CW ${String(r.cw).padStart(2,'0')}</b><span>${r.avgWeight?.toFixed(2)||'—'} kg</span><span>${r.waist||'—'} cm</span><span>${r.steps||'—'} kroków</span><span class="score">${r.score}/6</span><button class="btn" onclick="showReport('${r.id}')">Pokaż</button></div>`).join(''):'<p class="muted">Brak raportów w wybranym miesiącu.</p>';drawCombined(selected);drawLine('weightChart',selected,'avgWeight','kg','#63d58a');drawLine('waistChart',selected,'waist','cm','#66a9ff');buildTrend(all);};
document.getElementById('monthFilter')?.addEventListener('change',()=>window.renderHistory());
})();

// Cloud sync is kept in a separate module so the local dashboard remains usable offline.
const cloudSyncScript=document.createElement('script');
cloudSyncScript.src='sync.js';
cloudSyncScript.defer=true;
document.body.appendChild(cloudSyncScript);
